# Generated by Django 5.1.3 on 2024-11-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
