# Generated by Django 5.1.3 on 2024-11-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_steps_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steps',
            new_name='Step',
        ),
        migrations.AddField(
            model_name='recipe',
            name='step',
            field=models.ManyToManyField(to='recipes.step'),
        ),
    ]
