# Generated by Django 5.1.3 on 2024-11-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_steps_step_recipe_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='step',
            new_name='steps',
        ),
    ]
