# Generated by Django 5.1.3 on 2024-11-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipetag_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='text',
            field=models.CharField(choices=[('vegan', 'vegan'), ('vegan', 'vegetarian')], max_length=50, unique=True),
        ),
    ]
