# Generated by Django 5.1.3 on 2024-11-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_shoppinglist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
